import java.util.*;
public class random_num_game {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int randy = 1+(int)(Math.random()*9);
        boolean flag=true;

        System.out.print("\n\nRandom Number Generated!\nTry to guess the Number between (1 & 10) in 5 tries:\n\n");

        for (int i = 0; i < 5; i++) {
            int guess = sc.nextInt();
            if (guess<randy) {
                System.out.println("Too low!");
                continue;
            } else{
                if (guess>randy) {
                    System.out.println("Too High!");
                    continue;
                }
                else{
                    if (guess==randy) {
                        System.out.println("\nThat is the right number!\nCongrats!\n");
                        flag = false;
                        break;
                    }
                }
            }
        }

        if (flag) {
            System.out.print("\nOops! Out of trials!\nNumber generated by Computer : "+randy+"\n\n");
            System.out.print("Better luck next time LOL.\n\n");
        } else {
            System.out.print("You've Successfully completed the game!");
        }

    
        sc.close();
    }
}
